// Generated by player-native/ios/scripts/extract-videojs-icons.mjs from video.js 8.23.4's
// icon font. Do not edit.

/** The em of video.js's icon font: a glyph's path is in these units, y upwards. */
export const VIDEOJS_UNITS_PER_EM = 1792;

/** video.js's play glyph, as its big play button draws it. */
export const VIDEOJS_PLAY_PATH = 'M597.3333333333334 1418.6666666666665V373.3333333333333L1418.6666666666667 896z';
