/**
 * Stands in for `virtual:pwa-register/vue` in the desktop build.
 *
 * That module is generated by vite-plugin-pwa, which the desktop target does
 * not load: a service worker caching an app shell would fight the Electron
 * shell's own SPA fallback, and "a new version is available" belongs to the
 * app updater rather than to Workbox.
 *
 * `needRefresh` stays false, so `PwaUpdatePrompt` renders nothing and the
 * component needs no edit — the prompt is simply never shown.
 */

import { ref } from 'vue';

interface RegisterSWOptions {
    immediate?: boolean;
    onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void;
    onRegisteredSW?: (url: string, registration?: ServiceWorkerRegistration) => void;
    onRegisterError?: (error: unknown) => void;
    onNeedRefresh?: () => void;
    onOfflineReady?: () => void;
}

export function useRegisterSW(_options: RegisterSWOptions = {}) {
    // Deliberately not calling onRegistered: it installs a polling interval to
    // check for updates, and there is nothing to poll.
    return {
        needRefresh: ref(false),
        offlineReady: ref(false),
        updateServiceWorker: async (_reloadPage?: boolean) => {},
    };
}
