/**
 * The ISO 639-2 alpha-3 language codes, generated from the register itself.
 *
 * Source: the Library of Congress list at
 * `https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt`, which is the
 * maintenance agency's own file. Generated rather than hand-written because a
 * hand-written subset is a list of the codes whoever wrote it happened to think
 * of, and every omission rejects a language someone speaks.
 *
 * Both the bibliographic and terminology codes are included — `ger` and `deu`
 * are both German, and refusing one because the other exists would refuse a
 * correct answer. So are `mul` (multiple languages) and `und` (undetermined):
 * they are real codes, not escape hatches, and this app already emits `und`.
 *
 * 506 codes, plus the local-use range handled separately below.
 */
const LANGUAGE_ENTRIES: readonly (readonly [string, string])[] = [
    ['abk', 'Abkhazian'],
    ['ace', 'Achinese'],
    ['ach', 'Acoli'],
    ['ada', 'Adangme'],
    ['ady', 'Adyghe'],
    ['aar', 'Afar'],
    ['afh', 'Afrihili'],
    ['afr', 'Afrikaans'],
    ['afa', 'Afro-Asiatic languages'],
    ['ain', 'Ainu'],
    ['aka', 'Akan'],
    ['akk', 'Akkadian'],
    ['alb', 'Albanian'],
    ['sqi', 'Albanian'],
    ['ale', 'Aleut'],
    ['alg', 'Algonquian languages'],
    ['tut', 'Altaic languages'],
    ['amh', 'Amharic'],
    ['anp', 'Angika'],
    ['apa', 'Apache languages'],
    ['ara', 'Arabic'],
    ['arg', 'Aragonese'],
    ['arp', 'Arapaho'],
    ['arw', 'Arawak'],
    ['arm', 'Armenian'],
    ['hye', 'Armenian'],
    ['rup', 'Aromanian'],
    ['art', 'Artificial languages'],
    ['asm', 'Assamese'],
    ['ast', 'Asturian'],
    ['ath', 'Athapascan languages'],
    ['aus', 'Australian languages'],
    ['map', 'Austronesian languages'],
    ['ava', 'Avaric'],
    ['ave', 'Avestan'],
    ['awa', 'Awadhi'],
    ['aym', 'Aymara'],
    ['aze', 'Azerbaijani'],
    ['ban', 'Balinese'],
    ['bat', 'Baltic languages'],
    ['bal', 'Baluchi'],
    ['bam', 'Bambara'],
    ['bai', 'Bamileke languages'],
    ['bad', 'Banda languages'],
    ['bnt', 'Bantu languages'],
    ['bas', 'Basa'],
    ['bak', 'Bashkir'],
    ['baq', 'Basque'],
    ['eus', 'Basque'],
    ['btk', 'Batak languages'],
    ['bej', 'Beja'],
    ['bel', 'Belarusian'],
    ['bem', 'Bemba'],
    ['ben', 'Bengali'],
    ['ber', 'Berber languages'],
    ['bho', 'Bhojpuri'],
    ['bih', 'Bihari languages'],
    ['bik', 'Bikol'],
    ['bin', 'Bini'],
    ['bis', 'Bislama'],
    ['byn', 'Blin'],
    ['zbl', 'Blissymbols'],
    ['bos', 'Bosnian'],
    ['bra', 'Braj'],
    ['bre', 'Breton'],
    ['bug', 'Buginese'],
    ['bul', 'Bulgarian'],
    ['bua', 'Buriat'],
    ['bur', 'Burmese'],
    ['mya', 'Burmese'],
    ['cad', 'Caddo'],
    ['cat', 'Catalan'],
    ['cau', 'Caucasian languages'],
    ['ceb', 'Cebuano'],
    ['cel', 'Celtic languages'],
    ['cai', 'Central American Indian languages'],
    ['khm', 'Central Khmer'],
    ['chg', 'Chagatai'],
    ['cmc', 'Chamic languages'],
    ['cha', 'Chamorro'],
    ['che', 'Chechen'],
    ['chr', 'Cherokee'],
    ['chy', 'Cheyenne'],
    ['chb', 'Chibcha'],
    ['nya', 'Chichewa'],
    ['chi', 'Chinese'],
    ['zho', 'Chinese'],
    ['chn', 'Chinook jargon'],
    ['chp', 'Chipewyan'],
    ['cho', 'Choctaw'],
    ['chu', 'Church Slavic'],
    ['chk', 'Chuukese'],
    ['chv', 'Chuvash'],
    ['nwc', 'Classical Newari'],
    ['syc', 'Classical Syriac'],
    ['cop', 'Coptic'],
    ['cor', 'Cornish'],
    ['cos', 'Corsican'],
    ['cre', 'Cree'],
    ['mus', 'Creek'],
    ['crp', 'Creoles and pidgins'],
    ['cpe', 'Creoles and pidgins, English based'],
    ['cpf', 'Creoles and pidgins, French-based'],
    ['cpp', 'Creoles and pidgins, Portuguese-based'],
    ['crh', 'Crimean Tatar'],
    ['hrv', 'Croatian'],
    ['cus', 'Cushitic languages'],
    ['ces', 'Czech'],
    ['cze', 'Czech'],
    ['dak', 'Dakota'],
    ['dan', 'Danish'],
    ['dar', 'Dargwa'],
    ['del', 'Delaware'],
    ['din', 'Dinka'],
    ['div', 'Divehi'],
    ['doi', 'Dogri'],
    ['dra', 'Dravidian languages'],
    ['dua', 'Duala'],
    ['dut', 'Dutch'],
    ['nld', 'Dutch'],
    ['dum', 'Dutch, Middle (ca.1050-1350)'],
    ['dyu', 'Dyula'],
    ['dzo', 'Dzongkha'],
    ['frs', 'Eastern Frisian'],
    ['efi', 'Efik'],
    ['egy', 'Egyptian (Ancient)'],
    ['eka', 'Ekajuk'],
    ['elx', 'Elamite'],
    ['eng', 'English'],
    ['enm', 'English, Middle (1100-1500)'],
    ['ang', 'English, Old (ca.450-1100)'],
    ['myv', 'Erzya'],
    ['epo', 'Esperanto'],
    ['est', 'Estonian'],
    ['ewe', 'Ewe'],
    ['ewo', 'Ewondo'],
    ['fan', 'Fang'],
    ['fat', 'Fanti'],
    ['fao', 'Faroese'],
    ['fij', 'Fijian'],
    ['fil', 'Filipino'],
    ['fin', 'Finnish'],
    ['fiu', 'Finno-Ugrian languages'],
    ['fon', 'Fon'],
    ['fra', 'French'],
    ['fre', 'French'],
    ['frm', 'French, Middle (ca.1400-1600)'],
    ['fro', 'French, Old (842-ca.1400)'],
    ['fur', 'Friulian'],
    ['ful', 'Fulah'],
    ['gaa', 'Ga'],
    ['gla', 'Gaelic'],
    ['car', 'Galibi Carib'],
    ['glg', 'Galician'],
    ['lug', 'Ganda'],
    ['gay', 'Gayo'],
    ['gba', 'Gbaya'],
    ['gez', 'Geez'],
    ['geo', 'Georgian'],
    ['kat', 'Georgian'],
    ['deu', 'German'],
    ['ger', 'German'],
    ['gmh', 'German, Middle High (ca.1050-1500)'],
    ['goh', 'German, Old High (ca.750-1050)'],
    ['gem', 'Germanic languages'],
    ['gil', 'Gilbertese'],
    ['gon', 'Gondi'],
    ['gor', 'Gorontalo'],
    ['got', 'Gothic'],
    ['grb', 'Grebo'],
    ['grc', 'Greek, Ancient (to 1453)'],
    ['grn', 'Guarani'],
    ['guj', 'Gujarati'],
    ['gwi', 'Gwich\'in'],
    ['hai', 'Haida'],
    ['hat', 'Haitian'],
    ['hau', 'Hausa'],
    ['haw', 'Hawaiian'],
    ['heb', 'Hebrew'],
    ['her', 'Herero'],
    ['hil', 'Hiligaynon'],
    ['him', 'Himachali languages'],
    ['hin', 'Hindi'],
    ['hmo', 'Hiri Motu'],
    ['hit', 'Hittite'],
    ['hmn', 'Hmong'],
    ['hun', 'Hungarian'],
    ['hup', 'Hupa'],
    ['iba', 'Iban'],
    ['ice', 'Icelandic'],
    ['isl', 'Icelandic'],
    ['ido', 'Ido'],
    ['ibo', 'Igbo'],
    ['ijo', 'Ijo languages'],
    ['ilo', 'Iloko'],
    ['smn', 'Inari Sami'],
    ['inc', 'Indic languages'],
    ['ine', 'Indo-European languages'],
    ['ind', 'Indonesian'],
    ['inh', 'Ingush'],
    ['ina', 'Interlingua (International Auxiliary Language Association)'],
    ['ile', 'Interlingue'],
    ['iku', 'Inuktitut'],
    ['ipk', 'Inupiaq'],
    ['ira', 'Iranian languages'],
    ['gle', 'Irish'],
    ['mga', 'Irish, Middle (900-1200)'],
    ['sga', 'Irish, Old (to 900)'],
    ['iro', 'Iroquoian languages'],
    ['ita', 'Italian'],
    ['jpn', 'Japanese'],
    ['jav', 'Javanese'],
    ['jrb', 'Judeo-Arabic'],
    ['jpr', 'Judeo-Persian'],
    ['kbd', 'Kabardian'],
    ['kab', 'Kabyle'],
    ['kac', 'Kachin'],
    ['kal', 'Kalaallisut'],
    ['xal', 'Kalmyk'],
    ['kam', 'Kamba'],
    ['kan', 'Kannada'],
    ['kau', 'Kanuri'],
    ['kaa', 'Kara-Kalpak'],
    ['krc', 'Karachay-Balkar'],
    ['krl', 'Karelian'],
    ['kar', 'Karen languages'],
    ['kas', 'Kashmiri'],
    ['csb', 'Kashubian'],
    ['kaw', 'Kawi'],
    ['kaz', 'Kazakh'],
    ['kha', 'Khasi'],
    ['khi', 'Khoisan languages'],
    ['kho', 'Khotanese'],
    ['kik', 'Kikuyu'],
    ['kmb', 'Kimbundu'],
    ['kin', 'Kinyarwanda'],
    ['kir', 'Kirghiz'],
    ['tlh', 'Klingon'],
    ['kom', 'Komi'],
    ['kon', 'Kongo'],
    ['kok', 'Konkani'],
    ['kor', 'Korean'],
    ['kos', 'Kosraean'],
    ['kpe', 'Kpelle'],
    ['kro', 'Kru languages'],
    ['kua', 'Kuanyama'],
    ['kum', 'Kumyk'],
    ['kur', 'Kurdish'],
    ['kru', 'Kurukh'],
    ['kut', 'Kutenai'],
    ['lad', 'Ladino'],
    ['lah', 'Lahnda'],
    ['lam', 'Lamba'],
    ['day', 'Land Dayak languages'],
    ['lao', 'Lao'],
    ['lat', 'Latin'],
    ['lav', 'Latvian'],
    ['lez', 'Lezghian'],
    ['lim', 'Limburgan'],
    ['lin', 'Lingala'],
    ['lit', 'Lithuanian'],
    ['jbo', 'Lojban'],
    ['nds', 'Low German'],
    ['dsb', 'Lower Sorbian'],
    ['loz', 'Lozi'],
    ['lub', 'Luba-Katanga'],
    ['lua', 'Luba-Lulua'],
    ['lui', 'Luiseno'],
    ['smj', 'Lule Sami'],
    ['lun', 'Lunda'],
    ['luo', 'Luo (Kenya and Tanzania)'],
    ['lus', 'Lushai'],
    ['ltz', 'Luxembourgish'],
    ['mac', 'Macedonian'],
    ['mkd', 'Macedonian'],
    ['mad', 'Madurese'],
    ['mag', 'Magahi'],
    ['mai', 'Maithili'],
    ['mak', 'Makasar'],
    ['mlg', 'Malagasy'],
    ['may', 'Malay'],
    ['msa', 'Malay'],
    ['mal', 'Malayalam'],
    ['mlt', 'Maltese'],
    ['mnc', 'Manchu'],
    ['mdr', 'Mandar'],
    ['man', 'Mandingo'],
    ['mni', 'Manipuri'],
    ['mno', 'Manobo languages'],
    ['glv', 'Manx'],
    ['mao', 'Maori'],
    ['mri', 'Maori'],
    ['arn', 'Mapudungun'],
    ['mar', 'Marathi'],
    ['chm', 'Mari'],
    ['mah', 'Marshallese'],
    ['mwr', 'Marwari'],
    ['mas', 'Masai'],
    ['myn', 'Mayan languages'],
    ['men', 'Mende'],
    ['mic', 'Mi\'kmaq'],
    ['min', 'Minangkabau'],
    ['mwl', 'Mirandese'],
    ['ell', 'Modern Greek (1453-)'],
    ['gre', 'Modern Greek (1453-)'],
    ['moh', 'Mohawk'],
    ['mdf', 'Moksha'],
    ['mkh', 'Mon-Khmer languages'],
    ['lol', 'Mongo'],
    ['mon', 'Mongolian'],
    ['cnr', 'Montenegrin'],
    ['mos', 'Mossi'],
    ['mul', 'Multiple languages'],
    ['mun', 'Munda languages'],
    ['nqo', 'N\'Ko'],
    ['nah', 'Nahuatl languages'],
    ['nau', 'Nauru'],
    ['nav', 'Navajo'],
    ['ndo', 'Ndonga'],
    ['nap', 'Neapolitan'],
    ['new', 'Nepal Bhasa'],
    ['nep', 'Nepali'],
    ['nia', 'Nias'],
    ['nic', 'Niger-Kordofanian languages'],
    ['ssa', 'Nilo-Saharan languages'],
    ['niu', 'Niuean'],
    ['zxx', 'No linguistic content'],
    ['nog', 'Nogai'],
    ['non', 'Norse, Old'],
    ['nai', 'North American Indian languages'],
    ['nde', 'North Ndebele'],
    ['frr', 'Northern Frisian'],
    ['sme', 'Northern Sami'],
    ['nor', 'Norwegian'],
    ['nob', 'Norwegian Bokmål'],
    ['nno', 'Norwegian Nynorsk'],
    ['nub', 'Nubian languages'],
    ['nym', 'Nyamwezi'],
    ['nyn', 'Nyankole'],
    ['nyo', 'Nyoro'],
    ['nzi', 'Nzima'],
    ['oci', 'Occitan (post 1500)'],
    ['arc', 'Official Aramaic (700-300 BCE)'],
    ['oji', 'Ojibwa'],
    ['ori', 'Oriya'],
    ['orm', 'Oromo'],
    ['osa', 'Osage'],
    ['oss', 'Ossetian'],
    ['oto', 'Otomian languages'],
    ['pal', 'Pahlavi'],
    ['pau', 'Palauan'],
    ['pli', 'Pali'],
    ['pam', 'Pampanga'],
    ['pag', 'Pangasinan'],
    ['pan', 'Panjabi'],
    ['pap', 'Papiamento'],
    ['paa', 'Papuan languages'],
    ['nso', 'Pedi'],
    ['fas', 'Persian'],
    ['per', 'Persian'],
    ['peo', 'Persian, Old (ca.600-400 B.C.)'],
    ['phi', 'Philippine languages'],
    ['phn', 'Phoenician'],
    ['pon', 'Pohnpeian'],
    ['pol', 'Polish'],
    ['por', 'Portuguese'],
    ['pra', 'Prakrit languages'],
    ['pro', 'Provençal, Old (to 1500)'],
    ['pus', 'Pushto'],
    ['que', 'Quechua'],
    ['raj', 'Rajasthani'],
    ['rap', 'Rapanui'],
    ['rar', 'Rarotongan'],
    ['roa', 'Romance languages'],
    ['ron', 'Romanian'],
    ['rum', 'Romanian'],
    ['roh', 'Romansh'],
    ['rom', 'Romany'],
    ['run', 'Rundi'],
    ['rus', 'Russian'],
    ['sal', 'Salishan languages'],
    ['sam', 'Samaritan Aramaic'],
    ['smi', 'Sami languages'],
    ['smo', 'Samoan'],
    ['sad', 'Sandawe'],
    ['sag', 'Sango'],
    ['san', 'Sanskrit'],
    ['sat', 'Santali'],
    ['srd', 'Sardinian'],
    ['sas', 'Sasak'],
    ['sco', 'Scots'],
    ['sel', 'Selkup'],
    ['sem', 'Semitic languages'],
    ['srp', 'Serbian'],
    ['srr', 'Serer'],
    ['shn', 'Shan'],
    ['sna', 'Shona'],
    ['iii', 'Sichuan Yi'],
    ['scn', 'Sicilian'],
    ['sid', 'Sidamo'],
    ['sgn', 'Sign Languages'],
    ['bla', 'Siksika'],
    ['snd', 'Sindhi'],
    ['sin', 'Sinhala'],
    ['sit', 'Sino-Tibetan languages'],
    ['sio', 'Siouan languages'],
    ['sms', 'Skolt Sami'],
    ['den', 'Slave (Athapascan)'],
    ['sla', 'Slavic languages'],
    ['slk', 'Slovak'],
    ['slo', 'Slovak'],
    ['slv', 'Slovenian'],
    ['sog', 'Sogdian'],
    ['som', 'Somali'],
    ['son', 'Songhai languages'],
    ['snk', 'Soninke'],
    ['wen', 'Sorbian languages'],
    ['sot', 'Sotho, Southern'],
    ['sai', 'South American Indian languages'],
    ['nbl', 'South Ndebele'],
    ['alt', 'Southern Altai'],
    ['sma', 'Southern Sami'],
    ['spa', 'Spanish'],
    ['srn', 'Sranan Tongo'],
    ['zgh', 'Standard Moroccan Tamazight'],
    ['suk', 'Sukuma'],
    ['sux', 'Sumerian'],
    ['sun', 'Sundanese'],
    ['sus', 'Susu'],
    ['swa', 'Swahili'],
    ['ssw', 'Swati'],
    ['swe', 'Swedish'],
    ['gsw', 'Swiss German'],
    ['syr', 'Syriac'],
    ['tgl', 'Tagalog'],
    ['tah', 'Tahitian'],
    ['tai', 'Tai languages'],
    ['tgk', 'Tajik'],
    ['tmh', 'Tamashek'],
    ['tam', 'Tamil'],
    ['tat', 'Tatar'],
    ['tel', 'Telugu'],
    ['ter', 'Tereno'],
    ['tet', 'Tetum'],
    ['tha', 'Thai'],
    ['bod', 'Tibetan'],
    ['tib', 'Tibetan'],
    ['tig', 'Tigre'],
    ['tir', 'Tigrinya'],
    ['tem', 'Timne'],
    ['tiv', 'Tiv'],
    ['dgr', 'Tlicho'],
    ['tli', 'Tlingit'],
    ['tpi', 'Tok Pisin'],
    ['tkl', 'Tokelau'],
    ['tog', 'Tonga (Nyasa)'],
    ['ton', 'Tonga (Tonga Islands)'],
    ['tsi', 'Tsimshian'],
    ['tso', 'Tsonga'],
    ['tsn', 'Tswana'],
    ['tum', 'Tumbuka'],
    ['tup', 'Tupi languages'],
    ['tur', 'Turkish'],
    ['ota', 'Turkish, Ottoman (1500-1928)'],
    ['tuk', 'Turkmen'],
    ['tvl', 'Tuvalu'],
    ['tyv', 'Tuvinian'],
    ['twi', 'Twi'],
    ['udm', 'Udmurt'],
    ['uga', 'Ugaritic'],
    ['uig', 'Uighur'],
    ['ukr', 'Ukrainian'],
    ['umb', 'Umbundu'],
    ['mis', 'Uncoded languages'],
    ['und', 'Undetermined'],
    ['hsb', 'Upper Sorbian'],
    ['urd', 'Urdu'],
    ['uzb', 'Uzbek'],
    ['vai', 'Vai'],
    ['ven', 'Venda'],
    ['vie', 'Vietnamese'],
    ['vol', 'Volapük'],
    ['vot', 'Votic'],
    ['wak', 'Wakashan languages'],
    ['wln', 'Walloon'],
    ['war', 'Waray'],
    ['was', 'Washo'],
    ['cym', 'Welsh'],
    ['wel', 'Welsh'],
    ['fry', 'Western Frisian'],
    ['wal', 'Wolaitta'],
    ['wol', 'Wolof'],
    ['xho', 'Xhosa'],
    ['sah', 'Yakut'],
    ['yao', 'Yao'],
    ['yap', 'Yapese'],
    ['yid', 'Yiddish'],
    ['yor', 'Yoruba'],
    ['ypk', 'Yupik languages'],
    ['znd', 'Zande languages'],
    ['zap', 'Zapotec'],
    ['zza', 'Zaza'],
    ['zen', 'Zenaga'],
    ['zha', 'Zhuang'],
    ['zul', 'Zulu'],
    ['zun', 'Zuni'],
];

/** Code → English name, for showing what a code means. */
export const LANGUAGE_NAMES: ReadonlyMap<string, string> = new Map(
    LANGUAGE_ENTRIES
);

/** Every accepted code. */
export const ISO_639_2_CODES: ReadonlySet<string> = new Set(
    LANGUAGE_ENTRIES.map(([code]) => code)
);

/** `[code, name]` sorted by name, for a `<datalist>` or a picker. */
export const LANGUAGE_OPTIONS: readonly (readonly [string, string])[] =
    LANGUAGE_ENTRIES;

/**
 * What a typed language should be stored as.
 *
 * Trimmed and lower-cased, so `ENG`, ` eng ` and `eng` are one entry rather
 * than three — they reach `#EXT-X-MEDIA:LANGUAGE=` verbatim otherwise, and a
 * player matching on the string sees different languages.
 */
export function normalizeLanguageInput(raw: string | undefined | null): string {
    return (raw ?? '').trim().toLowerCase();
}

/**
 * `qaa` through `qtz`, which ISO 639-2 reserves for local use.
 *
 * The register lists these as one entry, `qaa-qtz`, because they are a range
 * rather than 520 assignments — so they cannot live in the set above, and the
 * literal string `qaa-qtz` is not itself a code. Accepted all the same: a
 * broadcaster with an unregistered language is the case the range exists for,
 * and refusing it would refuse the only correct answer they have. They are
 * deliberately absent from {@link LANGUAGE_OPTIONS}: there is nothing to
 * suggest, since only the person using one knows what it means.
 */
const LOCAL_USE_RANGE = /^q[a-t][a-z]$/;

/**
 * Whether a code may be stored.
 *
 * Empty passes: a track whose language nobody has said is a normal state, and
 * the encoder writes no `LANGUAGE` attribute for it rather than guessing. What
 * does not pass is a three-letter string that is not a language — `zzz` is the
 * shape of a code without being one, and it travels all the way to the player.
 */
export function isValidLanguageCode(code: string | undefined | null): boolean {
    const normalized = normalizeLanguageInput(code);
    return (
        normalized === ''
        || ISO_639_2_CODES.has(normalized)
        || LOCAL_USE_RANGE.test(normalized)
    );
}

/** The English name for a code, or undefined when it is not one. */
export function languageName(code: string | undefined | null): string | undefined {
    return LANGUAGE_NAMES.get(normalizeLanguageInput(code));
}
